# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  app-test:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    command: bash -c "npm run test; npm run vale"
